name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        sdk: ["3.4.0", stable]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dart-lang/setup-dart@7654d458321ee25acccccfdb86cd48bd95768ff1 # v1.8.0
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get
      - run: >-
          dart format --output=none --set-exit-if-changed
          bin example lib test tool/ci tool/generate_case_folding.dart
      - run: dart analyze --fatal-infos
      - run: dart test
      - if: matrix.os == 'ubuntu-latest' && matrix.sdk == 'stable'
        run: dart pub publish --dry-run
      - if: matrix.os == 'ubuntu-latest' && matrix.sdk == 'stable'
        run: dart pub -C tool/release get --enforce-lockfile
      - if: matrix.os == 'ubuntu-latest' && matrix.sdk == 'stable'
        working-directory: tool/release
        run: |
          dart format --output=none --set-exit-if-changed .
          dart analyze --fatal-infos
          dart run test
      - if: matrix.os == 'ubuntu-latest' && matrix.sdk == 'stable'
        env:
          ASSET: build/okf-ci-test
        run: >-
          dart --packages=tool/release/.dart_tool/package_config.json
          tool/release/grind.dart okf-build-binary
      - if: matrix.os == 'ubuntu-latest' && matrix.sdk == 'stable'
        run: ./build/okf-ci-test --version
